# Generated by Django 2.1 on 2019-01-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('cinema_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_cinema_list.Cinema')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='cinema_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_cinema_list.Cinema'),
        ),
    ]
